background_opacity .1
font_family JetBrainsMono Nerd Font
window_padding_width 10
cursor_shape block
shell_integration enabled no-cursor
map ctrl+u scroll_line_up
map ctrl+d scroll_line_down
cursor_trail 3

